name: Docker Image CI

on: [push]

jobs:
  test:
    name: Run Unit Test
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Maven Verify
        run: mvn -B clean verify
        
  docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-18.04
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Maven Build
        run: mvn -B clean install -Dtest -DfailIfNoTests=false
      - name: Logout
        run: docker logout
      - name: Login to Docker Hub
        run: printf ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/$REPO:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/$REPO:latest